// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alwkbmockbvckxoqyeus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsd2tibW9ja2J2Y2t4b3F5ZXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzE3NjUsImV4cCI6MjA1OTcwNzc2NX0.y8joludAgpGH-Hzzq9jnRfUB9pbx7x5EtgP1LBQdk6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);